### PR TITLE
Update Packages, Readme, and Version Compatibility

### PR DESCRIPTION
**Pull request by Bugs5382**
Hey there!

I update this package to work with Fustily 5.x, updated the packages, etc. Let me know if you have any questions!

### CODE REVIEW

**Comment by greguz** [comment]
Hi, firstly, thank you for the PR!  Much appretiation for anyone who commits to OSS.

**Comment by greguz** [comment]
@Bugs5382 pipelines' are failing because of a semicolon inside `fastify-kubernetes.js`. You can check the error with the `npm run lint` command.

I have to also ask you to revert the version upgrade. I will do that after the PR.

**Comment by Bugs5382** [comment]
@greguz  Done 👍

**Comment by Bugs5382** [comment]
You can edit my repo if needed. CHANGEME.MD was updated.

**Review by greguz — APPROVED** [review]

**Pull request merged**
